import type { Metadata } from "next";
import localFont from "next/font/local";
import { Indie_Flower } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/NavBar";

// Initialize Firebase at Next.js startup - import ensures it runs before any pages load
// This must be imported at the top level of layout.tsx to ensure it runs first
import "./lib/firebase-client";

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Google font
const indieFlower = Indie_Flower({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-indie-flower',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Maclellan Family Pictures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${indieFlower.variable}`}>
      <body className="font-sans antialiased bg-[#f5e6d3]">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}